{{- if .Values.secrets.create }}
{{- if .Values.secrets.existingSecret }}
{{- fail "secrets.create and secrets.existingSecret are mutually exclusive" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shadowshield.fullname" . }}
  labels:
    {{- include "shadowshield.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
